pipeline{
    agent any

    stages{
        stage("build"){
agent{
        docker{
           image 'maven:3.6.1-jdk-8-slim'
           args '-v m2cache:/root/.m2'
        }
    }          
steps{
              echo "Building worker app ..."
              dir("worker"){
                sh 'mvn compile'
              }
          }  
        }
        stage("test"){
          agent{
        docker{
           image 'maven:3.6.1-jdk-8-slim'
           args '-v m2cache:/root/.m2'
        }
    }
          steps{
              echo "Testing worker app ..."
              dir("worker"){
                sh 'mvn clean test'
              }
          }  
        }
        stage("package"){
         agent{
        docker{
           image 'maven:3.6.1-jdk-8-slim'
           args '-v m2cache:/root/.m2'
        }
    } 
         steps{
              echo "Packaging worker app ..."
              dir("worker"){
                sh 'mvn package'
              }
          }  
        }

       stage('docker-package'){
         agent any
         steps{
           echo 'Packaging worker app with docker'
           script{
             docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
             def workerImage = docker.build("justgurpreet/worker:v${env.BUILD_ID}", "./worker")
             workerImage.push()
 	     workerImage.push("latest")
             }		
 	    } 
         }
       }
    }
    
    post{
        always{
            /*archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo "Building multibranch pipeline for worker is completed..."*/
            echo 'the job is complete'
        }
    }
}
