pipeline{
    agent any
    
    tools{
        maven 'maven 3.6.1'
    }

    stages{
        stage("build"){
          steps{
              echo "Building worker app ..."
              dir("worker"){
                sh 'mvn compile'
              }
          }  
        }
        stage("test"){
          steps{
              echo "Testing worker app ..."
              dir("worker"){
                sh 'mvn clean test'
              }
          }  
        }
        stage("package"){
          steps{
              echo "Packaging worker app ..."
              dir("worker"){
                sh 'mvn package'
              }
          }  
        }
    }
    
    post{
        always{
            archiveArtifacts artifacts: 'build/libs/**/*.jar', fingerprint: true
            echo "Building multibranch pipeline for worker is completed..."
        }
    }
}
